### ISSUE TITLE
issues running codecgraph

### ISSUE THREAD

**Issue by somename9** [FioneraGH/codecgraph#2]
I am trying to run codecgraph on ubuntu 20.04 but I am always getting an error.

Steps that I did.
1. Installed graphviz
2. Download the repository from github by selecting Code-Download zip
2. extracted the zip file
3. Opened the folder with terminal
4. Entering "./codecgraph'

And then I always get the error "./codecgraph: 82: ./codecgraph.py: not found"

Am I doing something wrong or...?

**Comment by FioneraGH** [comment]
Check your work dir. Is it right？

**Comment by somename9** [comment]
Sorry forget to close this.
Issue was solved by using chmod +x
